from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone

from ai_hedge import legacy_port as legacy
from ai_hedge import trading_agents_adapter as ta


def test_deepseek_config_and_selected_analysts_exclude_market():
    assert ta.LLM_PROVIDER == "deepseek"
    assert ta.QUICK_THINK_LLM
    assert ta.DEEP_THINK_LLM
    assert ta.SELECTED_ANALYSTS == ["fundamentals", "news", "social"]
    assert "market" not in ta.SELECTED_ANALYSTS
    assert ta.EXCLUDED_ANALYSTS == ["market"]


def test_context_framing_includes_research_lens_and_excludes_market_payload():
    payload = ta.normalize_trading_agents_state(
        "TEST",
        {
            "fundamentals_report": "fundamental point",
            "news_report": "news point",
            "sentiment_report": "social point",
            "market_report": "moving average breakout should not leak",
            "investment_debate_state": {
                "bull_history": "bull case",
                "bear_history": "bear case",
                "judge_decision": "balanced view",
            },
            "risk_debate_state": {
                "aggressive_history": "risk up",
                "conservative_history": "risk down",
                "judge_decision": "risk view",
            },
            "final_trade_decision": "final committee view",
        },
        decision="committee output",
    )

    context = ta.build_trading_agents_context(payload)

    assert "independent research view generated by TradingAgents" in context
    assert "not a target price" in context
    assert "Fundamentals Report" in context
    assert "News Report" in context
    assert "Social / Sentiment Report" in context
    assert "Bull/Bear Debate" in context
    assert "Risk Debate" in context
    assert "Final Committee View" in context
    assert "moving average breakout" not in context
    assert "market_report" not in payload


def test_final_decision_metadata_is_preserved_but_excluded_from_valuation_context():
    raw_decision = """
**Rating**: BUY
**Executive Summary**: Durable growth with manageable execution risk.
**Investment Thesis**: Earnings quality supports the tactical view.
**Price Target**: $123.45
**Time Horizon**: 6-12 months
""".strip()
    payload = ta.normalize_trading_agents_state(
        "TEST",
        {
            "fundamentals_report": "Revenue quality is improving.",
            "final_trade_decision": raw_decision,
        },
        decision="BUY",
    )

    assert payload["final_committee_view"] == "BUY"
    assert payload["rating"] == "BUY"
    assert payload["price_target"] == 123.45
    assert payload["time_horizon"] == "6-12 months"

    context = ta.build_trading_agents_context(payload)
    assert "Durable growth" not in context
    assert "123.45" not in context
    assert "6-12 months" not in context
    assert "Price Target" not in context

    artifact = ta.build_trading_agents_artifact_text(payload)
    assert "## Independent Multi-Agent Research Lens" in artifact
    assert "TradingAgents Final Decision" not in artifact
    assert "123.45" not in artifact
    assert "6-12 months" not in artifact


def test_final_decision_metadata_accepts_common_markdown_json_and_range_shapes():
    markdown = ta._extract_final_decision_metadata(
        "**Rating:** Hold\n**Price Target:** approximately USD $210-$225\n**Time Horizon:** 6-9 months"
    )
    structured = ta._extract_final_decision_metadata(
        {"rating": "Overweight", "price_target": "1,234.50", "time-horizon": "12 months"}
    )

    assert markdown == {"rating": "Hold", "price_target": 210.0, "time_horizon": "6-9 months"}
    assert structured == {"rating": "Overweight", "price_target": 1234.5, "time_horizon": "12 months"}


def test_missing_tactical_metadata_repair_requires_numeric_target():
    class FakeStructured:
        def __init__(self, schema, owner):
            self.schema = schema
            self.owner = owner

        def invoke(self, prompt):
            self.owner.prompt = prompt
            return self.schema(rating="Hold", price_target=245.5, time_horizon="9 months")

    class FakeLlm:
        def __init__(self):
            self.prompt = ""

        def with_structured_output(self, schema):
            assert schema.model_fields["price_target"].is_required()
            return FakeStructured(schema, self)

        def invoke(self, _prompt):
            raise AssertionError("structured repair should be used")

    llm = FakeLlm()
    recovered = ta._recover_required_tactical_metadata(
        llm,
        "TEST",
        {
            "investment_plan": "Balanced plan.",
            "trader_investment_plan": "Wait for confirmation.",
            "risk_debate_state": {"history": "Risks and catalysts are balanced."},
        },
        "**Rating**: Hold\n**Time Horizon**: 9 months",
    )

    assert recovered == {"rating": "Hold", "price_target": 245.5, "time_horizon": "9 months"}
    assert "do not use or imitate any AI Hedge valuation target" in llm.prompt


def test_compact_payload_keeps_brief_and_drops_verbose_sections(monkeypatch):
    payload = ta.normalize_trading_agents_state(
        "TEST",
        {
            "fundamentals_report": "fundamental point " * 100,
            "news_report": "news point " * 100,
            "sentiment_report": "social point " * 100,
            "investment_debate_state": {"bull_history": "bull", "bear_history": "bear"},
            "risk_debate_state": {"neutral_history": "risk"},
        },
        decision="committee output",
    )
    monkeypatch.setattr(ta, "_summarize_trading_agents_payload", lambda _payload, api_key="": "compact brief")

    compact = ta.compact_trading_agents_payload(payload, api_key="key")
    context = ta.build_trading_agents_context(compact)

    assert compact["status"] == "success"
    assert compact["compacted"] is True
    assert compact["research_brief"] == "compact brief"
    assert "fundamentals_report" not in compact
    assert "compact brief" in context
    assert "fundamental point" not in context


def test_compaction_keeps_tactical_metadata_out_of_generated_research_brief(monkeypatch):
    prompts = []
    payload = ta.normalize_trading_agents_state(
        "TEST",
        {
            "fundamentals_report": "fundamental evidence",
            "final_trade_decision": "**Price Target**: 88\n**Time Horizon**: 9 months",
            "risk_debate_state": {
                "judge_decision": "**Price Target**: 88\n**Time Horizon**: 9 months",
            },
        },
        decision="HOLD",
    )
    def fake_summary(**kwargs):
        prompts.append(kwargs["prompt"])
        return "Business remains stable.\nPrice Target: 999\nTime Horizon: 1 month"

    monkeypatch.setattr(legacy, "deepseek_simple_text", fake_summary)

    compact = ta.compact_trading_agents_payload(payload, api_key="key")

    assert compact["price_target"] == 88
    assert compact["time_horizon"] == "9 months"
    assert compact["rating"] == "HOLD"
    assert compact["research_brief"] == "Business remains stable."
    assert "999" not in ta.build_trading_agents_context(compact)
    assert len(prompts) == 1
    assert "88" not in prompts[0]
    assert "9 months" not in prompts[0]


def test_required_target_portfolio_manager_contract():
    class FakeStructured:
        def __init__(self, schema, owner):
            self.schema = schema
            self.owner = owner

        def invoke(self, prompt):
            self.owner.prompt = prompt
            return self.schema(
                rating="Underweight",
                executive_summary="Reduce exposure.",
                investment_thesis="Risk outweighs reward.",
                price_target=210,
                time_horizon="6 months",
            )

    class FakeLlm:
        def __init__(self):
            self.schema = None
            self.prompt = ""

        def with_structured_output(self, schema):
            self.schema = schema
            return FakeStructured(schema, self)

        def invoke(self, _prompt):
            raise AssertionError("structured output should be used")

    llm = FakeLlm()
    node = ta._create_required_target_portfolio_manager(llm)
    state = {
        "company_of_interest": "IBM",
        "investment_plan": "Reduce exposure.",
        "trader_investment_plan": "Sell into strength.",
        "risk_debate_state": {
            "history": "Risks dominate.",
            "aggressive_history": "Aggressive view.",
            "conservative_history": "Conservative view.",
            "neutral_history": "Neutral view.",
            "current_aggressive_response": "",
            "current_conservative_response": "",
            "current_neutral_response": "",
            "count": 3,
        },
    }

    result = node(state)

    assert llm.schema.model_fields["price_target"].is_required()
    assert llm.schema.model_fields["time_horizon"].is_required()
    assert "Always provide one numeric **Price Target**" in llm.prompt
    assert "**Price Target**: 210.0" in result["final_trade_decision"]
    assert "**Time Horizon**: 6 months" in result["final_trade_decision"]


def test_deepseek_reasoner_skips_structured_tool_choice_for_managers():
    class Response:
        content = "**Rating**: Hold\n\n**Price Target**: 210\n\n**Time Horizon**: 6 months"

    class FakeReasoner:
        model_name = "deepseek-reasoner"

        def __init__(self):
            self.invocations = 0

        def with_structured_output(self, _schema):
            raise AssertionError("reasoner must not bind structured tool output")

        def invoke(self, _prompt):
            self.invocations += 1
            return Response()

    llm = FakeReasoner()
    assert ta._supports_structured_output(llm) is False

    portfolio_node = ta._create_required_target_portfolio_manager(llm)
    portfolio_result = portfolio_node(
        {
            "company_of_interest": "IBM",
            "investment_plan": "Balanced plan.",
            "trader_investment_plan": "Wait.",
            "risk_debate_state": {
                "history": "Balanced risks.",
                "aggressive_history": "",
                "conservative_history": "",
                "neutral_history": "",
                "current_aggressive_response": "",
                "current_conservative_response": "",
                "current_neutral_response": "",
                "count": 3,
            },
        }
    )
    assert "**Price Target**: 210" in portfolio_result["final_trade_decision"]

    research_node = ta._create_deepseek_compatible_research_manager(llm)
    research_result = research_node(
        {
            "company_of_interest": "IBM",
            "investment_debate_state": {
                "history": "Bull and bear evidence.",
                "bear_history": "Bear evidence.",
                "bull_history": "Bull evidence.",
                "count": 2,
            },
        }
    )
    assert "**Rating**: Hold" in research_result["investment_plan"]
    assert llm.invocations == 2


def test_summarize_uses_observed_legacy_deepseek_wrapper(monkeypatch):
    calls = []

    def fake_deepseek_simple_text(**kwargs):
        calls.append(kwargs)
        return "observed compact brief"

    monkeypatch.setattr(legacy, "deepseek_simple_text", fake_deepseek_simple_text)
    payload = ta.normalize_trading_agents_state(
        "TEST",
        {
            "fundamentals_report": "fundamental point",
            "news_report": "news point",
            "sentiment_report": "social point",
        },
        decision="committee output",
    )

    brief = ta._summarize_trading_agents_payload(payload, api_key="key")

    assert brief == "observed compact brief"
    assert len(calls) == 1
    assert calls[0]["model"] == ta.SUMMARY_LLM
    assert calls[0]["temperature"] == 0.1
    assert calls[0]["short_answer"] is False
    assert "TradingAgents raw transcript:" in calls[0]["prompt"]
    assert "Do not use any other Markdown headers or subheaders" in calls[0]["prompt"]


def test_summarize_preserves_brief_above_legacy_character_limit(monkeypatch):
    brief = ("Earlier evidence. " * 550) + (
        "\n\n### What Valuators Should Watch\n"
        "Operating margin trajectory near 22%: continued gross-margin discipline."
    )
    assert 9_000 < len(brief) < ta.COMPACT_BRIEF_MAX_CHARS
    monkeypatch.setattr(legacy, "deepseek_simple_text", lambda **_kwargs: brief)
    payload = ta.normalize_trading_agents_state(
        "TEST",
        {"fundamentals_report": "fundamental point"},
        decision="committee output",
    )

    result = ta._summarize_trading_agents_payload(payload, api_key="key")

    assert result == brief
    assert result.endswith("continued gross-margin discipline.")
    assert "[Truncated]" not in result


def test_reuse_accepts_fresh_success_with_matching_config(tmp_path):
    now = datetime(2026, 5, 27, tzinfo=timezone.utc)
    old_dir = tmp_path / "outputs" / "_site_runs" / "old" / "TEST"
    new_dir = tmp_path / "outputs" / "_site_runs" / "new" / "TEST"
    old_dir.mkdir(parents=True)
    new_dir.mkdir(parents=True)
    payload = {
        "status": "success",
        "ticker": "TEST",
        "generated_at": (now - timedelta(days=2)).isoformat(),
        "adapter_version": ta.ADAPTER_VERSION,
        "config_version": ta.CONFIG_VERSION,
        "selected_analysts": ta.SELECTED_ANALYSTS,
        "fundamentals_report": "fresh enough",
    }
    artifact = old_dir / "TEST_trading_agents.json"
    artifact.write_text(json.dumps(payload), encoding="utf-8")
    (old_dir / "TEST_trading_agents.txt").write_text("text", encoding="utf-8")

    found = ta.find_reusable_trading_agents_artifact(output_dir=new_dir, ticker="TEST", now=now)

    assert found is not None
    assert found[0] == artifact.resolve()


def test_reuse_rejects_stale_failure_and_version_mismatches(tmp_path):
    now = datetime(2026, 5, 27, tzinfo=timezone.utc)
    new_dir = tmp_path / "outputs" / "_site_runs" / "new" / "TEST"
    new_dir.mkdir(parents=True)
    cases = [
        ("stale", "success", now - timedelta(days=10), ta.ADAPTER_VERSION, ta.CONFIG_VERSION),
        ("failed", "unavailable", now - timedelta(days=1), ta.ADAPTER_VERSION, ta.CONFIG_VERSION),
        ("adapter", "success", now - timedelta(days=1), "old-adapter", ta.CONFIG_VERSION),
        ("config", "success", now - timedelta(days=1), ta.ADAPTER_VERSION, "old-config"),
    ]
    for name, status, generated_at, adapter_version, config_version in cases:
        directory = tmp_path / "outputs" / "_site_runs" / name / "TEST"
        directory.mkdir(parents=True)
        payload = {
            "status": status,
            "ticker": "TEST",
            "generated_at": generated_at.isoformat(),
            "adapter_version": adapter_version,
            "config_version": config_version,
            "selected_analysts": ta.SELECTED_ANALYSTS,
        }
        (directory / "TEST_trading_agents.json").write_text(json.dumps(payload), encoding="utf-8")

    found = ta.find_reusable_trading_agents_artifact(output_dir=new_dir, ticker="TEST", now=now)

    assert found is None


def test_propagate_helper_supports_v024_signature_without_asset_type():
    class Graph:
        def __init__(self):
            self.calls = []

        def propagate(self, ticker, trade_date):
            self.calls.append((ticker, trade_date))
            return {"fundamentals_report": "ok"}, "decision"

    graph = Graph()

    state, decision = ta._propagate_trading_agents_graph(graph, "AAPL", "2026-05-27")

    assert graph.calls == [("AAPL", "2026-05-27")]
    assert state["fundamentals_report"] == "ok"
    assert decision == "decision"


def test_propagate_helper_keeps_asset_type_when_supported():
    class Graph:
        def __init__(self):
            self.calls = []

        def propagate(self, ticker, trade_date, *, asset_type):
            self.calls.append((ticker, trade_date, asset_type))
            return {"fundamentals_report": "ok"}, "decision"

    graph = Graph()

    ta._propagate_trading_agents_graph(graph, "AAPL", "2026-05-27")

    assert graph.calls == [("AAPL", "2026-05-27", "stock")]
