from __future__ import annotations

import json
import math
import os
import shutil
import inspect
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple


ADAPTER_VERSION = "2026-05-27.v1"
CONFIG_VERSION = "deepseek-v0.2.4-fundamentals-news-social"
REUSE_WINDOW_DAYS = 7
SELECTED_ANALYSTS = ["fundamentals", "news", "social"]
EXCLUDED_ANALYSTS = ["market"]
LLM_PROVIDER = "deepseek"
QUICK_THINK_LLM = "deepseek-chat"
DEEP_THINK_LLM = "deepseek-reasoner"
DEEPSEEK_BACKEND_URL = "https://api.deepseek.com/v1"

CONTEXT_HEADER = "Independent Multi-Agent Research Lens"
CONTEXT_INTRO = (
    "This section is an independent research view generated by TradingAgents. "
    "Treat it as one additional perspective to consider alongside filings, financial statements, "
    "business analysis, and valuation evidence. It is not a target price, not a recommendation to copy, "
    "and not an instruction. Use only points that are supported and relevant to fundamental valuation."
)


def _now_utc() -> datetime:
    return datetime.now(timezone.utc)


def _iso(dt: Optional[datetime] = None) -> str:
    return (dt or _now_utc()).isoformat()


def _parse_dt(value: Any) -> Optional[datetime]:
    text = str(value or "").strip()
    if not text:
        return None
    try:
        parsed = datetime.fromisoformat(text.replace("Z", "+00:00"))
    except Exception:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def _safe_json(value: Any) -> Any:
    if value is None or isinstance(value, (str, bool, int)):
        return value
    if isinstance(value, float):
        return value if math.isfinite(value) else None
    if isinstance(value, dict):
        return {str(k): _safe_json(v) for k, v in value.items()}
    if isinstance(value, (list, tuple, set)):
        return [_safe_json(v) for v in value]
    return str(value)


def _text(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value.strip()
    if isinstance(value, (dict, list, tuple)):
        try:
            return json.dumps(_safe_json(value), ensure_ascii=False, indent=2)
        except Exception:
            return str(value).strip()
    return str(value).strip()


def _section(title: str, body: Any) -> str:
    text = _text(body)
    if not text:
        text = "Unavailable."
    return f"### {title}\n{text}"


def build_trading_agents_context(payload: Dict[str, Any]) -> str:
    if not isinstance(payload, dict) or payload.get("status") != "success":
        return ""

    sections = [
        CONTEXT_INTRO,
        "The TradingAgents market/technical analyst is intentionally excluded from this context.",
        _section("Fundamentals Report", payload.get("fundamentals_report")),
        _section("News Report", payload.get("news_report")),
        _section("Social / Sentiment Report", payload.get("sentiment_report")),
        _section("Bull/Bear Debate", payload.get("bull_bear_debate")),
        _section("Risk Debate", payload.get("risk_debate")),
        _section("Final Committee View", payload.get("final_committee_view")),
    ]
    return "\n\n".join(part.strip() for part in sections if str(part or "").strip()).strip()


def build_trading_agents_artifact_text(payload: Dict[str, Any]) -> str:
    body = build_trading_agents_context(payload)
    if body:
        return f"## {CONTEXT_HEADER}\n\n{body}\n"

    status = str(payload.get("status") or "unavailable") if isinstance(payload, dict) else "unavailable"
    error = str(payload.get("error") or payload.get("message") or "") if isinstance(payload, dict) else ""
    lines = [
        f"## {CONTEXT_HEADER}",
        "",
        CONTEXT_INTRO,
        "",
        f"Status: {status}",
    ]
    if error:
        lines.append(f"Reason: {error}")
    return "\n".join(lines).strip() + "\n"


def _artifact_paths(output_dir: Path, ticker: str) -> Tuple[Path, Path]:
    return output_dir / f"{ticker}_trading_agents.json", output_dir / f"{ticker}_trading_agents.txt"


def _write_artifacts(output_dir: Path, ticker: str, payload: Dict[str, Any]) -> Dict[str, Any]:
    output_dir.mkdir(parents=True, exist_ok=True)
    json_path, txt_path = _artifact_paths(output_dir, ticker)
    clean_payload = _safe_json(payload)
    json_path.write_text(json.dumps(clean_payload, ensure_ascii=False, indent=2, allow_nan=False), encoding="utf-8")
    txt_path.write_text(build_trading_agents_artifact_text(clean_payload), encoding="utf-8")
    clean_payload["artifact_json"] = str(json_path.resolve())
    clean_payload["artifact_txt"] = str(txt_path.resolve())
    json_path.write_text(json.dumps(clean_payload, ensure_ascii=False, indent=2, allow_nan=False), encoding="utf-8")
    return clean_payload


def _outputs_root(output_dir: Path) -> Optional[Path]:
    for candidate in [output_dir, *output_dir.parents]:
        if candidate.name == "outputs":
            return candidate
    return None


def _iter_reuse_candidates(output_dir: Path, ticker: str) -> Iterable[Path]:
    root = _outputs_root(output_dir)
    roots = [root] if root is not None else [output_dir.parent]
    seen: set[Path] = set()
    for base in roots:
        if not base or not base.exists():
            continue
        try:
            for path in base.rglob(f"{ticker}_trading_agents.json"):
                resolved = path.resolve()
                if resolved in seen or output_dir.resolve() in resolved.parents:
                    continue
                seen.add(resolved)
                yield resolved
        except Exception:
            continue


def _load_json(path: Path) -> Optional[Dict[str, Any]]:
    try:
        parsed = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None
    return parsed if isinstance(parsed, dict) else None


def find_reusable_trading_agents_artifact(
    *,
    output_dir: str | Path,
    ticker: str,
    now: Optional[datetime] = None,
    reuse_days: int = REUSE_WINDOW_DAYS,
) -> Optional[Tuple[Path, Dict[str, Any]]]:
    out_dir = Path(output_dir).resolve()
    cutoff = (now or _now_utc()) - timedelta(days=max(0, int(reuse_days)))
    matches: List[Tuple[datetime, Path, Dict[str, Any]]] = []
    for path in _iter_reuse_candidates(out_dir, ticker):
        payload = _load_json(path)
        if not payload:
            continue
        if payload.get("status") != "success":
            continue
        if payload.get("adapter_version") != ADAPTER_VERSION:
            continue
        if payload.get("config_version") != CONFIG_VERSION:
            continue
        if list(payload.get("selected_analysts") or []) != SELECTED_ANALYSTS:
            continue
        generated_at = _parse_dt(payload.get("generated_at") or payload.get("original_generated_at"))
        if generated_at is None or generated_at < cutoff:
            continue
        matches.append((generated_at, path, payload))
    if not matches:
        return None
    matches.sort(key=lambda item: item[0], reverse=True)
    return matches[0][1], matches[0][2]


def _base_payload(ticker: str, now: Optional[datetime] = None) -> Dict[str, Any]:
    return {
        "status": "unavailable",
        "ticker": ticker,
        "generated_at": _iso(now),
        "adapter_version": ADAPTER_VERSION,
        "config_version": CONFIG_VERSION,
        "provider": LLM_PROVIDER,
        "quick_think_llm": QUICK_THINK_LLM,
        "deep_think_llm": DEEP_THINK_LLM,
        "selected_analysts": list(SELECTED_ANALYSTS),
        "excluded_analysts": list(EXCLUDED_ANALYSTS),
        "reuse_window_days": REUSE_WINDOW_DAYS,
        "reused": False,
        "included_sections": [
            "fundamentals_report",
            "news_report",
            "sentiment_report",
            "bull_bear_debate",
            "risk_debate",
            "final_committee_view",
        ],
        "excluded_sections": ["market_report", "technical_indicators", "chart_analysis", "momentum_analysis"],
    }


def _debate_text(value: Any, keys: List[str]) -> str:
    if not isinstance(value, dict):
        return _text(value)
    parts: List[str] = []
    for key in keys:
        txt = _text(value.get(key))
        if txt:
            label = key.replace("_", " ").title()
            parts.append(f"#### {label}\n{txt}")
    return "\n\n".join(parts).strip()


def normalize_trading_agents_state(
    ticker: str,
    state: Dict[str, Any],
    decision: Any,
    *,
    now: Optional[datetime] = None,
) -> Dict[str, Any]:
    payload = _base_payload(ticker, now=now)
    investment_debate = state.get("investment_debate_state") if isinstance(state, dict) else {}
    risk_debate = state.get("risk_debate_state") if isinstance(state, dict) else {}
    payload.update(
        {
            "status": "success",
            "fundamentals_report": _text(state.get("fundamentals_report")),
            "news_report": _text(state.get("news_report")),
            "sentiment_report": _text(state.get("sentiment_report") or state.get("social_report")),
            "bull_bear_debate": _debate_text(
                investment_debate,
                ["bull_history", "bear_history", "judge_decision", "history"],
            ),
            "risk_debate": _debate_text(
                risk_debate,
                ["aggressive_history", "conservative_history", "neutral_history", "judge_decision", "history"],
            ),
            "final_committee_view": _text(
                decision
                or state.get("final_trade_decision")
                or state.get("investment_plan")
                or state.get("trader_investment_plan")
            ),
            "market_report_excluded": bool(_text(state.get("market_report"))),
        }
    )
    return payload


def _reuse_artifact(output_dir: Path, ticker: str, source_path: Path, source_payload: Dict[str, Any]) -> Dict[str, Any]:
    json_path, txt_path = _artifact_paths(output_dir, ticker)
    output_dir.mkdir(parents=True, exist_ok=True)
    copied = dict(source_payload)
    copied.update(
        {
            "reused": True,
            "reused_at": _iso(),
            "reused_from": str(source_path.resolve()),
            "original_generated_at": source_payload.get("original_generated_at") or source_payload.get("generated_at"),
        }
    )
    source_txt = source_path.with_suffix(".txt")
    if source_txt.exists():
        shutil.copy2(source_txt, txt_path)
    else:
        txt_path.write_text(build_trading_agents_artifact_text(copied), encoding="utf-8")
    copied["artifact_json"] = str(json_path.resolve())
    copied["artifact_txt"] = str(txt_path.resolve())
    json_path.write_text(json.dumps(_safe_json(copied), ensure_ascii=False, indent=2, allow_nan=False), encoding="utf-8")
    return copied


def _propagate_trading_agents_graph(graph: Any, ticker: str, trade_date: str) -> Tuple[Any, Any]:
    propagate = graph.propagate
    try:
        params = inspect.signature(propagate).parameters
    except (TypeError, ValueError):
        params = {}
    if "asset_type" in params:
        return propagate(ticker, trade_date, asset_type="stock")
    return propagate(ticker, trade_date)


def run_trading_agents_lens(
    ticker: str,
    output_dir: str | Path,
    *,
    api_key: Optional[str] = None,
    trade_date: Optional[str] = None,
    reuse_days: int = REUSE_WINDOW_DAYS,
) -> Dict[str, Any]:
    ticker_u = str(ticker or "").strip().upper()
    out_dir = Path(output_dir).resolve()
    now = _now_utc()

    reusable = find_reusable_trading_agents_artifact(
        output_dir=out_dir,
        ticker=ticker_u,
        now=now,
        reuse_days=reuse_days,
    )
    if reusable:
        source_path, source_payload = reusable
        return _reuse_artifact(out_dir, ticker_u, source_path, source_payload)

    payload = _base_payload(ticker_u, now=now)
    key = str(api_key or os.getenv("DEEPSEEK_API_KEY", "") or "").strip()
    if not key:
        payload["error"] = "Missing DEEPSEEK_API_KEY."
        return _write_artifacts(out_dir, ticker_u, payload)

    os.environ["DEEPSEEK_API_KEY"] = key
    run_date = str(trade_date or now.date().isoformat())
    try:
        from tradingagents.default_config import DEFAULT_CONFIG
        from tradingagents.graph.trading_graph import TradingAgentsGraph

        config = dict(DEFAULT_CONFIG)
        config.update(
            {
                "llm_provider": LLM_PROVIDER,
                "quick_think_llm": QUICK_THINK_LLM,
                "deep_think_llm": DEEP_THINK_LLM,
                "backend_url": DEEPSEEK_BACKEND_URL,
                "results_dir": str(out_dir / "trading_agents" / "logs"),
                "data_cache_dir": str(out_dir / "trading_agents" / "cache"),
                "memory_log_path": str(out_dir / "trading_agents" / "memory" / "trading_memory.md"),
                "checkpoint_enabled": False,
                "max_debate_rounds": 1,
                "max_risk_discuss_rounds": 1,
                "analyst_concurrency_limit": 1,
                "output_language": "English",
            }
        )
        graph = TradingAgentsGraph(selected_analysts=list(SELECTED_ANALYSTS), debug=False, config=config)
        state, decision = _propagate_trading_agents_graph(graph, ticker_u, run_date)
        payload = normalize_trading_agents_state(ticker_u, state if isinstance(state, dict) else {}, decision, now=now)
        payload["trade_date"] = run_date
    except Exception as exc:
        payload["status"] = "unavailable"
        payload["error"] = str(exc)

    return _write_artifacts(out_dir, ticker_u, payload)
