from __future__ import annotations

import inspect
import json
import math
import os
import re
import shutil
import threading
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple


ADAPTER_VERSION = "2026-08-22.v6"
CONFIG_VERSION = "deepseek-v0.2.4-fundamentals-news-social"
REUSE_WINDOW_DAYS = 7
SELECTED_ANALYSTS = ["fundamentals", "news", "social"]
EXCLUDED_ANALYSTS = ["market"]
LLM_PROVIDER = "deepseek"
QUICK_THINK_LLM = "deepseek-chat"
DEEP_THINK_LLM = "deepseek-reasoner"
SUMMARY_LLM = "deepseek-v4-flash"
DEEPSEEK_BACKEND_URL = "https://api.deepseek.com/v1"
# The summary prompt allows up to roughly 1,600 words. Keep a modest safety
# margin above that expected output so the final section is not cut mid-sentence.
COMPACT_BRIEF_MAX_CHARS = 12_000
_GRAPH_SETUP_LOCK = threading.Lock()

_TACTICAL_CONTEXT_LINE_RE = re.compile(
    r"\b(?:price[\s_-]*target|target[\s_-]*price|entry[\s_-]*price|stop[\s_-]*loss|"
    r"time[\s_-]*horizon|holding[\s_-]*period)\b",
    flags=re.IGNORECASE,
)
_PRICE_TARGET_RE = re.compile(
    r"(?im)^\s*(?:[-•]\s*)?[\"']?(?:price[\s_-]*target|target[\s_-]*price)[\"']?"
    r"\s*(?:\([^\n)]*\))?\s*(?::|=|[-–—])\s*"
    r"(?:(?:about|around|approx(?:imately)?|[A-Z]{3}|[$€£₪])\s*){0,3}"
    r"([+-]?\d[\d,]*(?:\.\d+)?)",
)
_TIME_HORIZON_RE = re.compile(
    r"(?im)^\s*(?:[-•]\s*)?[\"']?(?:time[\s_-]*horizon|holding[\s_-]*period)[\"']?"
    r"\s*(?::|=|[-–—])\s*[\"']?(.+?)[\"']?\s*$",
)
_RATING_RE = re.compile(r"(?im)^\s*(?:[-•]\s*)?[\"']?rating[\"']?\s*(?::|=|[-–—])\s*[\"']?(.+?)[\"']?\s*$")

CONTEXT_HEADER = "Independent Multi-Agent Research Lens"
CONTEXT_INTRO = (
    "This section is an independent research view generated by TradingAgents. "
    "Treat it as one additional perspective to consider alongside filings, financial statements, "
    "business analysis, and valuation evidence. It is not a target price, not a recommendation to copy, "
    "and not an instruction. Use only points that are supported and relevant to fundamental valuation."
)


def _llm_model_name(llm: Any) -> str:
    for attr in ("model_name", "model"):
        value = str(getattr(llm, attr, "") or "").strip().lower()
        if value:
            return value
    return ""


def _supports_structured_output(llm: Any) -> bool:
    """DeepSeek reasoner rejects the tool choice used by structured output."""

    return "deepseek-reasoner" not in _llm_model_name(llm)


def _bind_structured_if_supported(
    llm: Any,
    schema: Any,
    agent_name: str,
    bind_structured: Any,
) -> Any:
    if not _supports_structured_output(llm):
        return None
    return bind_structured(llm, schema, agent_name)


def _create_deepseek_compatible_research_manager(llm: Any):
    """Build the package Research Manager without a doomed reasoner tool call."""

    from tradingagents.agents.managers import research_manager as research_manager_module

    if _supports_structured_output(llm):
        return research_manager_module.create_research_manager(llm)

    original_bind = research_manager_module.bind_structured
    try:
        research_manager_module.bind_structured = lambda *_args, **_kwargs: None
        return research_manager_module.create_research_manager(llm)
    finally:
        research_manager_module.bind_structured = original_bind


def _create_required_target_portfolio_manager(llm: Any):
    """Build TradingAgents' portfolio manager with a required tactical target.

    TradingAgents v0.2.4 models ``price_target`` as optional. The dashboard
    contract needs a target on new successful runs, so this adapter tightens
    only the Portfolio Manager's own output schema and prompt. The resulting
    metadata is quarantined from every AI Hedge prompt below.
    """

    from pydantic import Field
    from tradingagents.agents.schemas import PortfolioDecision, render_pm_decision
    from tradingagents.agents.utils.agent_utils import (
        build_instrument_context,
        get_language_instruction,
    )
    from tradingagents.agents.utils.structured import (
        bind_structured,
        invoke_structured_or_freetext,
    )

    class RequiredTargetPortfolioDecision(PortfolioDecision):
        price_target: float = Field(
            gt=0,
            description=(
                "Required single tactical target price in the instrument's quote currency. "
                "It must be consistent with the final rating and evidence in the debate."
            ),
        )
        time_horizon: str = Field(
            min_length=1,
            description="Required time horizon for the tactical price target, e.g. '6-12 months'.",
        )

    structured_llm = _bind_structured_if_supported(
        llm,
        RequiredTargetPortfolioDecision,
        "Portfolio Manager",
        bind_structured,
    )

    def portfolio_manager_node(state: Dict[str, Any]) -> Dict[str, Any]:
        instrument_context = build_instrument_context(state["company_of_interest"])
        risk_debate_state = state["risk_debate_state"]
        history = risk_debate_state["history"]
        research_plan = state["investment_plan"]
        trader_plan = state["trader_investment_plan"]
        past_context = state.get("past_context", "")
        lessons_line = (
            f"- Lessons from prior decisions and outcomes:\n{past_context}\n"
            if past_context
            else ""
        )

        prompt = f"""As the Portfolio Manager, synthesize the risk analysts' debate and deliver the final trading decision.

{instrument_context}

---

**Rating Scale** (use exactly one):
- **Buy**: Strong conviction to enter or add to position
- **Overweight**: Favorable outlook, gradually increase exposure
- **Hold**: Maintain current position, no action needed
- **Underweight**: Reduce exposure, take partial profits
- **Sell**: Exit position or avoid entry

**Required Tactical Output:**
- Always provide one numeric **Price Target** in the instrument's quote currency.
- Always provide a non-empty **Time Horizon** for that target.
- The target must be the Portfolio Manager's own conclusion from this TradingAgents debate.
- Do not omit these fields for Hold, Underweight, or Sell ratings.

**Context:**
- Research Manager's investment plan: **{research_plan}**
- Trader's transaction proposal: **{trader_plan}**
{lessons_line}**Risk Analysts Debate History:**
{history}

---

Be decisive and ground every conclusion in specific evidence from the analysts.{get_language_instruction()}"""

        final_trade_decision = invoke_structured_or_freetext(
            structured_llm,
            llm,
            prompt,
            render_pm_decision,
            "Portfolio Manager",
        )
        new_risk_debate_state = {
            "judge_decision": final_trade_decision,
            "history": risk_debate_state["history"],
            "aggressive_history": risk_debate_state["aggressive_history"],
            "conservative_history": risk_debate_state["conservative_history"],
            "neutral_history": risk_debate_state["neutral_history"],
            "latest_speaker": "Judge",
            "current_aggressive_response": risk_debate_state["current_aggressive_response"],
            "current_conservative_response": risk_debate_state["current_conservative_response"],
            "current_neutral_response": risk_debate_state["current_neutral_response"],
            "count": risk_debate_state["count"],
        }
        return {
            "risk_debate_state": new_risk_debate_state,
            "final_trade_decision": final_trade_decision,
        }

    return portfolio_manager_node


def _now_utc() -> datetime:
    return datetime.now(timezone.utc)


def _iso(dt: Optional[datetime] = None) -> str:
    return (dt or _now_utc()).isoformat()


def _parse_dt(value: Any) -> Optional[datetime]:
    text = str(value or "").strip()
    if not text:
        return None
    try:
        parsed = datetime.fromisoformat(text.replace("Z", "+00:00"))
    except Exception:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def _safe_json(value: Any) -> Any:
    if value is None or isinstance(value, (str, bool, int)):
        return value
    if isinstance(value, float):
        return value if math.isfinite(value) else None
    if isinstance(value, dict):
        return {str(k): _safe_json(v) for k, v in value.items()}
    if isinstance(value, (list, tuple, set)):
        return [_safe_json(v) for v in value]
    return str(value)


def _text(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value.strip()
    if isinstance(value, (dict, list, tuple)):
        try:
            return json.dumps(_safe_json(value), ensure_ascii=False, indent=2)
        except Exception:
            return str(value).strip()
    return str(value).strip()


def _trim_chars(value: str, limit: int) -> str:
    text = str(value or "").strip()
    if len(text) <= limit:
        return text
    return text[: max(0, int(limit))].rstrip() + "\n\n[Truncated]"


def _without_tactical_decision_lines(value: Any) -> str:
    """Remove tactical price/holding lines before content crosses a valuation boundary."""

    text = _text(value)
    if not text:
        return ""
    lines = [line for line in text.splitlines() if not _TACTICAL_CONTEXT_LINE_RE.search(line)]
    return re.sub(r"\n{3,}", "\n\n", "\n".join(lines)).strip()


def _clean_markdown_value(value: Any) -> str:
    return re.sub(r"\*+", "", _text(value)).strip()


def _structured_decision_mapping(value: Any) -> Dict[str, Any]:
    if isinstance(value, dict):
        raw = value
    else:
        dump = getattr(value, "model_dump", None)
        if not callable(dump):
            return {}
        try:
            raw = dump()
        except Exception:
            return {}
    if not isinstance(raw, dict):
        return {}
    return {
        re.sub(r"[\s-]+", "_", str(key).strip().lower()): item
        for key, item in raw.items()
    }


def _extract_final_decision_metadata(final_decision: Any, processed_decision: Any = None) -> Dict[str, Any]:
    structured = _structured_decision_mapping(final_decision)
    price_target: Optional[float] = None
    structured_target = structured.get("price_target", structured.get("target_price"))
    if structured_target is not None:
        try:
            parsed = float(str(structured_target).replace(",", "").replace("$", "").strip())
            if math.isfinite(parsed) and parsed > 0:
                price_target = parsed
        except Exception:
            price_target = None

    time_horizon = _clean_markdown_value(
        structured.get("time_horizon", structured.get("holding_period", ""))
    )
    rating = _clean_markdown_value(structured.get("rating", ""))

    for candidate in (final_decision, processed_decision):
        text = re.sub(r"[*`]", "", _text(candidate))
        if not text:
            continue
        if price_target is None:
            price_match = _PRICE_TARGET_RE.search(text)
            if price_match:
                try:
                    parsed = float(price_match.group(1).replace(",", ""))
                    if math.isfinite(parsed) and parsed > 0:
                        price_target = parsed
                except Exception:
                    price_target = None
        if not time_horizon:
            horizon_match = _TIME_HORIZON_RE.search(text)
            if horizon_match:
                time_horizon = _clean_markdown_value(horizon_match.group(1)).rstrip(",")
        if not rating:
            rating_match = _RATING_RE.search(text)
            if rating_match:
                rating = _clean_markdown_value(rating_match.group(1)).rstrip(",")

    if not rating:
        rating = _clean_markdown_value(processed_decision)

    return {
        "rating": rating,
        "price_target": price_target,
        "time_horizon": time_horizon,
    }


def _recover_required_tactical_metadata(
    llm: Any,
    ticker: str,
    state: Dict[str, Any],
    raw_final_decision: Any,
) -> Dict[str, Any]:
    """Retry only the quarantined TradingAgents tactical metadata contract."""

    from pydantic import BaseModel, Field
    from tradingagents.agents.utils.structured import bind_structured, invoke_structured_or_freetext

    class RequiredTacticalMetadata(BaseModel):
        rating: str = Field(min_length=1, description="One of Buy, Overweight, Hold, Underweight, or Sell.")
        price_target: float = Field(gt=0, description="One numeric target in the instrument's quote currency.")
        time_horizon: str = Field(min_length=1, description="The time horizon for the target.")

    def render(decision: RequiredTacticalMetadata) -> str:
        return (
            f"**Rating**: {decision.rating}\n\n"
            f"**Price Target**: {decision.price_target}\n\n"
            f"**Time Horizon**: {decision.time_horizon}"
        )

    risk_debate = state.get("risk_debate_state") if isinstance(state, dict) else {}
    prompt = f"""The Portfolio Manager decision for {ticker} did not yield every required tactical metadata field.
Repair the metadata using only the TradingAgents material below. This is a TradingAgents tactical decision; do not use or imitate any AI Hedge valuation target.

Return exactly one rating, one positive numeric price target in {ticker}'s quote currency, and one non-empty time horizon. The price target is required for Buy, Overweight, Hold, Underweight, and Sell.

Previous Portfolio Manager decision:
{_trim_chars(_text(raw_final_decision), 8_000)}

Research Manager plan:
{_trim_chars(_text(state.get('investment_plan')), 6_000)}

Trader plan:
{_trim_chars(_text(state.get('trader_investment_plan')), 6_000)}

Risk debate:
{_trim_chars(_text(risk_debate), 12_000)}
""".strip()
    structured_llm = _bind_structured_if_supported(
        llm,
        RequiredTacticalMetadata,
        "Portfolio Manager metadata repair",
        bind_structured,
    )
    repaired = invoke_structured_or_freetext(
        structured_llm,
        llm,
        prompt,
        render,
        "Portfolio Manager metadata repair",
    )
    return _extract_final_decision_metadata(repaired)


def _section(title: str, body: Any) -> str:
    text = _text(body)
    if not text:
        text = "Unavailable."
    return f"### {title}\n{text}"


def build_trading_agents_context(payload: Dict[str, Any]) -> str:
    if not isinstance(payload, dict) or payload.get("status") != "success":
        return ""
    research_brief = _without_tactical_decision_lines(payload.get("research_brief"))
    if research_brief:
        sections = [
            CONTEXT_INTRO,
            _section("Compact Research Brief", research_brief),
        ]
        return "\n\n".join(part.strip() for part in sections if str(part or "").strip()).strip()

    sections = [
        CONTEXT_INTRO,
        _section("Fundamentals Report", _without_tactical_decision_lines(payload.get("fundamentals_report"))),
        _section("News Report", _without_tactical_decision_lines(payload.get("news_report"))),
        _section("Social / Sentiment Report", _without_tactical_decision_lines(payload.get("sentiment_report"))),
        _section("Bull/Bear Debate", _without_tactical_decision_lines(payload.get("bull_bear_debate"))),
        _section("Risk Debate", _without_tactical_decision_lines(payload.get("risk_debate"))),
        _section("Final Committee View", _without_tactical_decision_lines(payload.get("final_committee_view"))),
    ]
    return "\n\n".join(part.strip() for part in sections if str(part or "").strip()).strip()


def build_trading_agents_artifact_text(payload: Dict[str, Any]) -> str:
    body = build_trading_agents_context(payload)
    if body:
        return f"## {CONTEXT_HEADER}\n\n{body}\n"

    status = str(payload.get("status") or "unavailable") if isinstance(payload, dict) else "unavailable"
    error = str(payload.get("error") or payload.get("message") or "") if isinstance(payload, dict) else ""
    lines = [
        f"## {CONTEXT_HEADER}",
        "",
        CONTEXT_INTRO,
        "",
        f"Status: {status}",
    ]
    if error:
        lines.append(f"Reason: {error}")
    return "\n".join(lines).strip() + "\n"


def _raw_trading_agents_bundle(payload: Dict[str, Any]) -> str:
    sections = [
        _section("Final Committee View", _without_tactical_decision_lines(payload.get("final_committee_view"))),
        _section("Fundamentals Report", _without_tactical_decision_lines(payload.get("fundamentals_report"))),
        _section("News Report", _without_tactical_decision_lines(payload.get("news_report"))),
        _section("Social / Sentiment Report", _without_tactical_decision_lines(payload.get("sentiment_report"))),
        _section("Bull/Bear Debate", _without_tactical_decision_lines(payload.get("bull_bear_debate"))),
        _section("Risk Debate", _without_tactical_decision_lines(payload.get("risk_debate"))),
    ]
    return "\n\n".join(part.strip() for part in sections if str(part or "").strip()).strip()


def _fallback_compact_research_brief(payload: Dict[str, Any]) -> str:
    pieces = []
    final_view = _without_tactical_decision_lines(payload.get("final_committee_view"))
    if final_view:
        pieces.append(f"### Final Committee View\n{_trim_chars(final_view, 1200)}")
    for title, key in [
        ("Fundamental Signals", "fundamentals_report"),
        ("News And Sentiment Signals", "news_report"),
        ("Social Sentiment Signals", "sentiment_report"),
        ("Bull/Bear Debate", "bull_bear_debate"),
        ("Risk Debate", "risk_debate"),
    ]:
        text = _without_tactical_decision_lines(payload.get(key))
        if text:
            pieces.append(f"### {title}\n{_trim_chars(text, 1400)}")
    return _trim_chars("\n\n".join(pieces).strip(), COMPACT_BRIEF_MAX_CHARS)


def _summarize_trading_agents_payload(payload: Dict[str, Any], *, api_key: str) -> str:
    raw_bundle = _raw_trading_agents_bundle(payload)
    if not raw_bundle:
        return ""
    key = str(api_key or "").strip()
    if not key:
        return _fallback_compact_research_brief(payload)

    prompt = f"""
You are compressing a verbose multi-agent equity research transcript into the canonical TradingAgents investment memory artifact.
This is the only TradingAgents artifact we will keep.
The goal is long-horizon valuation usefulness and retrieval efficiency.

Write a dense research brief for this TradingAgents raw transcript. Preserve the highest-signal ideas only.
Target length: typically 1,000-1,600 words, but optimize for signal density rather than strict length.

Preserve:
- business quality
- growth durability
- earnings quality
- margin structure and operating leverage
- free cash flow quality and capital intensity
- competitive positioning
- valuation-relevant macro exposure
- key catalysts
- core bull/bear thesis conflicts
- important uncertainty drivers

Rules:
- Keep it useful for valuation work: business quality, growth durability, earnings quality, margin drivers, capital intensity, competitive position, key news, sentiment, bull case, bear case, risk debate, and any other points that are relevant to fundamental valuation.
- Omit every TradingAgents price target, target price, entry price, stop-loss, time horizon, and holding period. These tactical fields are preserved separately and must never enter the valuation context.
- Do not add a score, instruction, or trading order.
- Do not include chart or technical-analysis claims.
- Do not mention that you are summarizing.
- If the transcript evidence is ordinary, mixed, or thin, say so plainly.
- Do not force a non-obvious insight when the transcript does not support one.
- Distinguish evidence, inference, and speculation.
- A neutral or low-conviction conclusion is acceptable.
- Do not make the research brief stronger than the transcript supports.
- Use Markdown with these headings exactly:
  ### Final Committee View
  ### Business And Fundamentals
  ### News And Sentiment
  ### Bull Case
  ### Bear Case
  ### Risk Debate
  ### What Valuators Should Watch
- Do not use any other Markdown headers or subheaders. Inside each section, use bullets, paragraphs, and **bold labels** only as needed for clarity.
- Be specific. Avoid generic filler.

TradingAgents raw transcript:
<TradingAgents_Raw>
{raw_bundle}
</TradingAgents_Raw>
""".strip()

    try:
        from ai_hedge import legacy_port as legacy

        summary = legacy.deepseek_simple_text(
            api_key=key,
            prompt=prompt,
            model=SUMMARY_LLM,
            temperature=0.1,
            timeout=(10.0, 180.0),
            short_answer=False,
        )
        summary = _text(summary)
        if summary:
            return _trim_chars(_without_tactical_decision_lines(summary), COMPACT_BRIEF_MAX_CHARS)
    except Exception:
        pass
    return _fallback_compact_research_brief(payload)


def compact_trading_agents_payload(payload: Dict[str, Any], *, api_key: str = "") -> Dict[str, Any]:
    if not isinstance(payload, dict) or payload.get("status") != "success":
        return payload
    brief = _summarize_trading_agents_payload(payload, api_key=api_key)
    compact = _base_payload(str(payload.get("ticker") or ""), now=_parse_dt(payload.get("generated_at")) or _now_utc())
    compact.update(
        {
            "status": "success",
            "trade_date": payload.get("trade_date"),
            "research_brief": brief,
            "final_committee_view": _text(payload.get("final_committee_view")),
            "rating": _text(payload.get("rating")),
            "price_target": payload.get("price_target"),
            "time_horizon": _text(payload.get("time_horizon")),
            "metadata_recovery_attempted": bool(payload.get("metadata_recovery_attempted")),
            "metadata_recovered": bool(payload.get("metadata_recovered")),
            "metadata_error": _text(payload.get("metadata_error")),
            "valuation_prompt_excluded_fields": [
                "price_target",
                "time_horizon",
                "entry_price",
                "stop_loss",
            ],
            "market_report_excluded": bool(payload.get("market_report_excluded")),
            "compacted": True,
            "summary_model": SUMMARY_LLM if str(api_key or "").strip() else "fallback",
        }
    )
    return compact


def _artifact_paths(output_dir: Path, ticker: str) -> Tuple[Path, Path]:
    return output_dir / f"{ticker}_trading_agents.json", output_dir / f"{ticker}_trading_agents.txt"


def _write_artifacts(output_dir: Path, ticker: str, payload: Dict[str, Any]) -> Dict[str, Any]:
    output_dir.mkdir(parents=True, exist_ok=True)
    json_path, txt_path = _artifact_paths(output_dir, ticker)
    clean_payload = _safe_json(payload)
    json_path.write_text(json.dumps(clean_payload, ensure_ascii=False, indent=2, allow_nan=False), encoding="utf-8")
    txt_path.write_text(build_trading_agents_artifact_text(clean_payload), encoding="utf-8")
    clean_payload["artifact_json"] = str(json_path.resolve())
    clean_payload["artifact_txt"] = str(txt_path.resolve())
    json_path.write_text(json.dumps(clean_payload, ensure_ascii=False, indent=2, allow_nan=False), encoding="utf-8")
    return clean_payload


def _outputs_root(output_dir: Path) -> Optional[Path]:
    for candidate in [output_dir, *output_dir.parents]:
        if candidate.name == "outputs":
            return candidate
    return None


def _iter_reuse_candidates(output_dir: Path, ticker: str) -> Iterable[Path]:
    root = _outputs_root(output_dir)
    roots = [root] if root is not None else [output_dir.parent]
    seen: set[Path] = set()
    for base in roots:
        if not base or not base.exists():
            continue
        try:
            for path in base.rglob(f"{ticker}_trading_agents.json"):
                resolved = path.resolve()
                if resolved in seen or output_dir.resolve() in resolved.parents:
                    continue
                seen.add(resolved)
                yield resolved
        except Exception:
            continue


def _load_json(path: Path) -> Optional[Dict[str, Any]]:
    try:
        parsed = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None
    return parsed if isinstance(parsed, dict) else None


def find_reusable_trading_agents_artifact(
    *,
    output_dir: str | Path,
    ticker: str,
    now: Optional[datetime] = None,
    reuse_days: int = REUSE_WINDOW_DAYS,
) -> Optional[Tuple[Path, Dict[str, Any]]]:
    out_dir = Path(output_dir).resolve()
    cutoff = (now or _now_utc()) - timedelta(days=max(0, int(reuse_days)))
    matches: List[Tuple[datetime, Path, Dict[str, Any]]] = []
    for path in _iter_reuse_candidates(out_dir, ticker):
        payload = _load_json(path)
        if not payload:
            continue
        if payload.get("status") != "success":
            continue
        if payload.get("adapter_version") != ADAPTER_VERSION:
            continue
        if payload.get("config_version") != CONFIG_VERSION:
            continue
        if list(payload.get("selected_analysts") or []) != SELECTED_ANALYSTS:
            continue
        generated_at = _parse_dt(payload.get("generated_at") or payload.get("original_generated_at"))
        if generated_at is None or generated_at < cutoff:
            continue
        matches.append((generated_at, path, payload))
    if not matches:
        return None
    matches.sort(key=lambda item: item[0], reverse=True)
    return matches[0][1], matches[0][2]


def _base_payload(ticker: str, now: Optional[datetime] = None) -> Dict[str, Any]:
    return {
        "status": "unavailable",
        "ticker": ticker,
        "generated_at": _iso(now),
        "adapter_version": ADAPTER_VERSION,
        "config_version": CONFIG_VERSION,
        "provider": LLM_PROVIDER,
        "quick_think_llm": QUICK_THINK_LLM,
        "deep_think_llm": DEEP_THINK_LLM,
        "selected_analysts": list(SELECTED_ANALYSTS),
        "excluded_analysts": list(EXCLUDED_ANALYSTS),
        "reuse_window_days": REUSE_WINDOW_DAYS,
        "reused": False,
        "rating": "",
        "price_target": None,
        "time_horizon": "",
        "metadata_recovery_attempted": False,
        "metadata_recovered": False,
        "metadata_error": "",
        "valuation_prompt_excluded_fields": [
            "price_target",
            "time_horizon",
            "entry_price",
            "stop_loss",
        ],
        "included_sections": [
            "fundamentals_report",
            "news_report",
            "sentiment_report",
            "bull_bear_debate",
            "risk_debate",
            "final_committee_view",
        ],
        "excluded_sections": ["market_report", "technical_indicators", "chart_analysis", "momentum_analysis"],
    }


def _debate_text(value: Any, keys: List[str]) -> str:
    if not isinstance(value, dict):
        return _text(value)
    parts: List[str] = []
    for key in keys:
        txt = _text(value.get(key))
        if txt:
            label = key.replace("_", " ").title()
            parts.append(f"#### {label}\n{txt}")
    return "\n\n".join(parts).strip()


def normalize_trading_agents_state(
    ticker: str,
    state: Dict[str, Any],
    decision: Any,
    *,
    now: Optional[datetime] = None,
) -> Dict[str, Any]:
    payload = _base_payload(ticker, now=now)
    investment_debate = state.get("investment_debate_state") if isinstance(state, dict) else {}
    risk_debate = state.get("risk_debate_state") if isinstance(state, dict) else {}
    raw_final_decision = _text(
        state.get("final_trade_decision")
        or state.get("investment_plan")
        or state.get("trader_investment_plan")
    )
    metadata = _extract_final_decision_metadata(raw_final_decision, decision)
    display_decision = _clean_markdown_value(decision) or metadata["rating"]
    payload.update(
        {
            "status": "success",
            "fundamentals_report": _text(state.get("fundamentals_report")),
            "news_report": _text(state.get("news_report")),
            "sentiment_report": _text(state.get("sentiment_report") or state.get("social_report")),
            "bull_bear_debate": _debate_text(
                investment_debate,
                ["bull_history", "bear_history", "judge_decision", "history"],
            ),
            "risk_debate": _debate_text(
                risk_debate,
                ["aggressive_history", "conservative_history", "neutral_history", "judge_decision", "history"],
            ),
            # Preserve the compact v2 report contract. The raw Portfolio
            # Manager prose is used only for metadata extraction above and is
            # never stored in a field that crosses an AI Hedge prompt boundary.
            "final_committee_view": display_decision,
            "rating": metadata["rating"],
            "price_target": metadata["price_target"],
            "time_horizon": metadata["time_horizon"],
            "market_report_excluded": bool(_text(state.get("market_report"))),
        }
    )
    return payload


def _reuse_artifact(output_dir: Path, ticker: str, source_path: Path, source_payload: Dict[str, Any]) -> Dict[str, Any]:
    json_path, txt_path = _artifact_paths(output_dir, ticker)
    output_dir.mkdir(parents=True, exist_ok=True)
    copied = dict(source_payload)
    copied.update(
        {
            "reused": True,
            "reused_at": _iso(),
            "reused_from": str(source_path.resolve()),
            "original_generated_at": source_payload.get("original_generated_at") or source_payload.get("generated_at"),
        }
    )
    source_txt = source_path.with_suffix(".txt")
    if source_txt.exists():
        shutil.copy2(source_txt, txt_path)
    else:
        txt_path.write_text(build_trading_agents_artifact_text(copied), encoding="utf-8")
    copied["artifact_json"] = str(json_path.resolve())
    copied["artifact_txt"] = str(txt_path.resolve())
    json_path.write_text(json.dumps(_safe_json(copied), ensure_ascii=False, indent=2, allow_nan=False), encoding="utf-8")
    return copied


def _propagate_trading_agents_graph(graph: Any, ticker: str, trade_date: str) -> Tuple[Any, Any]:
    propagate = graph.propagate
    try:
        params = inspect.signature(propagate).parameters
    except (TypeError, ValueError):
        params = {}
    if "asset_type" in params:
        return propagate(ticker, trade_date, asset_type="stock")
    return propagate(ticker, trade_date)


def run_trading_agents_lens(
    ticker: str,
    output_dir: str | Path,
    *,
    api_key: Optional[str] = None,
    trade_date: Optional[str] = None,
    reuse_days: int = REUSE_WINDOW_DAYS,
) -> Dict[str, Any]:
    ticker_u = str(ticker or "").strip().upper()
    out_dir = Path(output_dir).resolve()
    now = _now_utc()

    reusable = find_reusable_trading_agents_artifact(
        output_dir=out_dir,
        ticker=ticker_u,
        now=now,
        reuse_days=reuse_days,
    )
    if reusable:
        source_path, source_payload = reusable
        return _reuse_artifact(out_dir, ticker_u, source_path, source_payload)

    payload = _base_payload(ticker_u, now=now)
    key = str(api_key or os.getenv("DEEPSEEK_API_KEY", "") or "").strip()
    if not key:
        payload["error"] = "Missing DEEPSEEK_API_KEY."
        return _write_artifacts(out_dir, ticker_u, payload)

    os.environ["DEEPSEEK_API_KEY"] = key
    run_date = str(trade_date or now.date().isoformat())
    try:
        from tradingagents.default_config import DEFAULT_CONFIG
        from tradingagents.graph import setup as graph_setup
        from tradingagents.graph.trading_graph import TradingAgentsGraph

        # Tighten only TradingAgents' own final output contract. This target
        # is extracted into dashboard metadata and never enters AI Hedge
        # analysis, dashboard-extraction, or valuation prompts.
        config = dict(DEFAULT_CONFIG)
        config.update(
            {
                "llm_provider": LLM_PROVIDER,
                "quick_think_llm": QUICK_THINK_LLM,
                "deep_think_llm": DEEP_THINK_LLM,
                "backend_url": DEEPSEEK_BACKEND_URL,
                "results_dir": str(out_dir / "trading_agents" / "logs"),
                "data_cache_dir": str(out_dir / "trading_agents" / "cache"),
                "memory_log_path": str(out_dir / "trading_agents" / "memory" / "trading_memory.md"),
                "checkpoint_enabled": False,
                "max_debate_rounds": 1,
                "max_risk_discuss_rounds": 1,
                "analyst_concurrency_limit": 1,
                "output_language": "English",
            }
        )
        # TradingAgents resolves this factory while constructing the graph.
        # Restore the package global immediately afterward so the adapter does
        # not change unrelated graph construction in this process.
        with _GRAPH_SETUP_LOCK:
            original_create_portfolio_manager = graph_setup.create_portfolio_manager
            original_create_research_manager = graph_setup.create_research_manager
            try:
                graph_setup.create_portfolio_manager = _create_required_target_portfolio_manager
                graph_setup.create_research_manager = _create_deepseek_compatible_research_manager
                graph = TradingAgentsGraph(selected_analysts=list(SELECTED_ANALYSTS), debug=False, config=config)
            finally:
                graph_setup.create_portfolio_manager = original_create_portfolio_manager
                graph_setup.create_research_manager = original_create_research_manager
        state, decision = _propagate_trading_agents_graph(graph, ticker_u, run_date)
        state_dict = state if isinstance(state, dict) else {}
        payload = normalize_trading_agents_state(ticker_u, state_dict, decision, now=now)
        if payload.get("price_target") is None or not _text(payload.get("time_horizon")):
            payload["metadata_recovery_attempted"] = True
            try:
                recovered = _recover_required_tactical_metadata(
                    graph.deep_thinking_llm,
                    ticker_u,
                    state_dict,
                    state_dict.get("final_trade_decision"),
                )
                for field in ("rating", "price_target", "time_horizon"):
                    if payload.get(field) in (None, "") and recovered.get(field) not in (None, ""):
                        payload[field] = recovered[field]
                payload["metadata_recovered"] = bool(
                    payload.get("price_target") is not None and _text(payload.get("time_horizon"))
                )
            except Exception as recovery_error:
                payload["metadata_error"] = f"Metadata repair failed: {recovery_error}"
            if payload.get("price_target") is None or not _text(payload.get("time_horizon")):
                payload["metadata_error"] = payload.get("metadata_error") or (
                    "TradingAgents completed, but required tactical target metadata remained incomplete after repair."
                )
        payload["trade_date"] = run_date
        payload = compact_trading_agents_payload(payload, api_key=key)
    except Exception as exc:
        payload["status"] = "unavailable"
        payload["error"] = str(exc)

    return _write_artifacts(out_dir, ticker_u, payload)
